FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -o server ./cmd/server/main.go

FROM alpine:3.19

RUN apk add --no-cache sqlite-libs

WORKDIR /app

COPY --from=builder /app/server .

EXPOSE 8080

CMD ["./server"]
