inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
grpc_inference_port=7070
grpc_management_port=7071

model_store=../model_store
load_models=fault_diagnosis.mar

number_of_netty_threads=4
job_queue_size=1000
async_logging=true

max_request_size=65535000
max_response_size=65535000
default_workers_per_model=2

enable_envvars_config=true
install_py_dep_per_model=true

prefer_direct_buffer=true
decode_input_request=true
enable_grpc_server=true

cors_allowed_origin=*
cors_allowed_methods=GET, POST, PUT, OPTIONS
cors_allowed_headers=Content-Type, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token
